export const AuthConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_LOADING: "USER_LOGIN_LOADING",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR: "USER_LOGIN_ERROR",

  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_LOADING: "USER_LOGOUT_LOADING",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_ERROR: "USER_LOGOUT_ERROR",

  SEND_OTP_REQUEST: "SEND_OTP_REQUEST",
  SEND_OTP_LOADING: "SEND_OTP_LOADING",
  SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
  SEND_OTP_ERROR: "SEND_OTP_ERROR",
  SEND_OTP_IS_OPEN: "SEND_OTP_IS_OPEN",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_LOADING: "USER_REGISTER_LOADING",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_ERROR: "USER_REGISTER_ERROR",

  USER_SIGN_UP_REQUEST: "USER_SIGN_UP_REQUEST",
  USER_SIGN_UP_LOADING: "USER_SIGN_UP_LOADING",
  USER_SIGN_UP_SUCCESS: "USER_SIGN_UP_SUCCESS",
  USER_SIGN_UP_ERROR: "USER_SIGN_UP_ERROR",

  USER_OTP_REQUEST: "USER_OTP_REQUEST",
  USER_OTP_LOADING: "USER_OTP_LOADING",
  USER_OTP_SUCCESS: "USER_OTP_SUCCESS",
  USER_OTP_ERROR: "USER_OTP_ERROR",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_LOADING: "FORGOT_PASSWORD_LOADING",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR ",

  FORGOT_OTP_VERIFY_REQUEST: "FORGOT_OTP_VERIFY_REQUEST",
  FORGOT_OTP_VERIFY_LOADING: "FORGOT_OTP_VERIFY_LOADING",
  FORGOT_OTP_VERIFY_SUCCESS: "FORGOT_OTP_VERIFY_SUCCESS",
  FORGOT_OTP_VERIFY_ERROR: "FORGOT_OTP_VERIFY_ERROR ",
  FORGOT_OTP_VERIFY_POP_UP: "FORGOT_OTP_VERIFY_POP_UP ",

  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_LOADING: "RESET_PASSWORD_LOADING",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR ",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_LOADING: "CHANGE_PASSWORD_LOADING",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_ERROR: "CHANGE_PASSWORD_ERROR ",

  UPDATE_USER_PROFILE_REQUEST: "UPDATE_USER_PROFILE_REQUEST",
  UPDATE_USER_PROFILE_LOADING: "UPDATE_USER_PROFILE_LOADING",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_ERROR: "UPDATE_USER_PROFILE_ERROR ",

  IMAGE_UPLOAD_REQUEST: "IMAGE_UPLOAD_REQUEST",
  IMAGE_UPLOAD_LOADING: "IMAGE_UPLOAD_LOADING",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  IMAGE_UPLOAD_ERROR: "IMAGE_UPLOAD_ERROR ",

  UPDATE_USER_DATA: "UPDATE_USER_DATA ",
  UPDATE_TEMP_DATA: "UPDATE_TEMP_DATA ",
  UPDATE_AUTHORIZATION: "UPDATE_AUTHORIZATION ",
  UPDATE_WALLET_ADDRESS: "UPDATE_WALLET_ADDRESS ",

  CREATE_NFT_FORM_REQUEST: "CREATE_NFT_FORM_REQUEST",
  CREATE_NFT_FORM_LOADING: "CREATE_NFT_FORM_LOADING",
  CREATE_NFT_FORM_SUCCESS: "CREATE_NFT_FORM_SUCCESS",
  CREATE_NFT_FORM_ERROR: "CREATE_NFT_FORM_ERROR",

  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_LOADING: "GET_CATEGORY_LOADING",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_ERROR: "GET_CATEGORY_ERROR",

  CREATE_COLLECTION_REQUEST: "CREATE_COLLECTION_REQUEST",
  CREATE_COLLECTION_LOADING: "CREATE_COLLECTION_LOADING",
  CREATE_COLLECTION_SUCCESS: "CREATE_COLLECTION_SUCCESS",
  CREATE_COLLECTION_ERROR: "CREATE_COLLECTION_ERROR",

  GET_NFT_REQUEST: "GET_NFT_REQUEST",
  GET_NFT_LOADING: "GET_NFT_LOADING",
  GET_NFT_SUCCESS: "GET_NFT_SUCCESS",
  GET_NFT_ERROR: "GET_NFT_ERROR",

  GET_COLLECTION_REQUEST: "GET_COLLECTION_REQUEST",
  GET_COLLECTION_LOADING: "GET_COLLECTION_LOADING",
  GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
  GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",

  GET_NFT_BY_ID_REQUEST: "GET_NFT_BY_ID_REQUEST",
  GET_NFT_BY_ID_LOADING: "GET_NFT_BY_ID_LOADING",
  GET_NFT_BY_ID_SUCCESS: "GET_NFT_BY_ID_SUCCESS",
  GET_NFT_BY_ID_ERROR: "GET_NFT_BY_ID_ERROR",

  GET_COLLECTION_BY_ID_REQUEST: "GET_COLLECTION_BY_ID_REQUEST",
  GET_COLLECTION_BY_ID_LOADING: "GET_COLLECTION_BY_ID_LOADING",
  GET_COLLECTION_BY_ID_SUCCESS: "GET_COLLECTION_BY_ID_SUCCESS",
  GET_COLLECTION_BY_ID_ERROR: "GET_COLLECTION_BY_ID_ERROR",

  GET_USER_COLLECTION_REQUEST: "GET_USER_COLLECTION_REQUEST",
  GET_USER_COLLECTION_LOADING: "GET_USER_COLLECTION_LOADING",
  GET_USER_COLLECTION_SUCCESS: "GET_USER_COLLECTION_SUCCESS",
  GET_USER_COLLECTION_ERROR: "GET_USER_COLLECTION_ERROR",

  GET_APP_SETTINGS_REQUEST: "GET_APP_SETTINGS_REQUEST",
  GET_APP_SETTINGS_LOADING: "GET_APP_SETTINGS_LOADING",
  GET_APP_SETTINGS_SUCCESS: "GET_APP_SETTINGS_SUCCESS",
  GET_APP_SETTINGS_ERROR: "GET_APP_SETTINGS_ERROR",

  UPDATE_COLLECTION_REQUEST: "UPDATE_COLLECTION_REQUEST",
  UPDATE_COLLECTION_LOADING: "UPDATE_COLLECTION_LOADING",
  UPDATE_COLLECTION_SUCCESS: "UPDATE_COLLECTION_SUCCESS",
  UPDATE_COLLECTION_ERROR: "UPDATE_COLLECTION_ERROR",

  UPDATE_NFT_REQUEST: "UPDATE_NFT_REQUEST",
  UPDATE_NFT_LOADING: "UPDATE_NFT_LOADING",
  UPDATE_NFT_SUCCESS: "UPDATE_NFT_SUCCESS",
  UPDATE_NFT_ERROR: "UPDATE_NFT_ERROR",

  BUY_NFT_REQUEST: "BUY_NFT_REQUEST",
  BUY_NFT_LOADING: "BUY_NFT_LOADING",
  BUY_NFT_SUCCESS: "BUY_NFT_SUCCESS",
  BUY_NFT_ERROR: "BUY_NFT_ERROR",

  SHOW_DIALOG: "SHOW_DIALOG",
  HIDE_DIALOGE: "HIDE_DIALOGE",
};
